name: Olá mundo
on: [push]
jobs:
  ola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Olá mundo
        run: echo "Olá mundo!"

     