name: Olá mundo
on: [push]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
    
jobs:
 ola_mundo_jobs:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Olá mundo
        run: echo "Olá mundo!"

     