name: Olá mundo
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Olá mundo
        run: echo "Olá mundo!"

     